### ISSUE TITLE
视频评论区被控评了，来这贴一条

### ISSUE THREAD

**Issue by orangelckc** [gaogaotiantian/soss#2]
阿里云OSS有现成的管理客户端啊，自己本地做下加密解密就好，自己的数据最好还是做多硬盘备份，成本比上云要划算很多，云厂商都是初始便宜，续费贵的要死，而且一旦密钥泄漏了，虽然别人看不到你的内容，但是可以给你删了，让你付费赎回，过来人奉劝各位小白，白嫖玩玩就好，数据无价，千万谨慎！

**Comment by HisAtri** [comment]
正确的，这种需求上对象存储毫无必要甚至徒增成本和风险，更何况阿里云的垃圾服务

**Comment by huanyue6660** [comment]
果照丢了就丢了
