### ISSUE TITLE
真是吃相难看，控制评论区，战老的脸都被丢光了

### ISSUE THREAD

**Issue by orangelckc** [gaogaotiantian/soss#6]
评论区设置关键字吞评论，还删评论，那咋不直接关了评论区呢？

后来只能发倒图评论，但是几小时后又被手动删除了，我把原评论图片贴在这里，大家看看我要是说的不对的，您使劲怼我，我公开道歉，后面还有我小号录屏的视频证明我当时确实发出去了，但是现在无了，可以确认是UP手动删除的。

如果还有其他有志之士的评论被删除了，也请你们贴在下方，感谢！

![WechatIMG862](https://github.com/gaogaotiantian/soss/assets/48410934/98556d4c-8c6b-4ca6-a792-20efe89727bf)

https://github.com/gaogaotiantian/soss/assets/48410934/ffc67b45-4318-42d1-9a05-6ad4a6d42f4f

**Comment by SatoMatsuzaka** [comment]
删评拉黑知识星球老粉，我只能说这逼把事情做绝了。亏我评论还尽可能克制地提醒，这下不得不正义切割了。

不过好消息是商单视频24小时了播放量没破万。

**Comment by fireinrain** [comment]
确实 我在评论取，我发过一个评论，这方法压根不可取，完全就是商单行为。然后就被删除评论了。
只能说 强如微软高薪开发 也逃不过商单真香的定律啊。况且 完全就是伪需求。是因为接了这么个商单 想出来这么个整活。
而不是想整活 才接了商单
